name: Auto Api

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 */6 * * *
  watch:
    types: started
   
jobs:
  autoapi:
    name: Office365 E5 Trial
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install requests cryptography
    - name: Test Api
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        FERNET_KEY: ${{ secrets.FERNET_KEY }}
      run: |
        python ./AutoApi/autoapi.py     
    - name: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update new refresh_token" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}