name: Epic

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
   
jobs:
  epic:
    name: Epic free games
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies 
      run: |
        git clone https://github.com/Revadike/epicgames-freebies-claimer.git epic
        cd epic && npm install   
    - name: Get free games
      env:
        USERNAME: ${{ secrets.EPIC_USERNAME }}
        PASSWORD: ${{ secrets.EPIC_PASSWORD }}
      run: |
        cd epic && node gimme_free_epic_shit $USERNAME $PASSWORD
